name: Plex Media Server (public build)
description: Plex organizes your video, music, and photo collections and streams them to all of your screens. plexinc/pms-docker:public
category: Organize
version: 1.0
maintainer: Cody White <codyrwhite@icloud.com>
license: MIT
projectURL: https://github.com/codyrwhite/rancher-catalog