app:
  restart: always
  image: plexinc/pms-docker:public
  ports:
   - "32400:32400"
  net: "host"
  cap_drop:
    - NET_ADMIN
  volumes_from:
  - data
  volumes:
  - /media/storage/tvshows:/mnt/tvshows
  - /media/storage/movies:/mnt/movies
  - /media/storage/music:/mnt/music
  labels:
    io.rancher.sidekicks: data
    depot.lb.link: true
    depot.lb.port: 32400
    depot.app.type: plex
data:
  image: plexinc/pms-docker:public
  labels:
    io.rancher.container.start_once: true
  volumes:
  - /srv/plex/config
  - /srv/plex/data